### ISSUE TITLE
`/report/team/:id` route

### ISSUE THREAD

**Issue by m-242** [SECCDC/flexo#24]
This must return the score of the team (sum of all attacks category multiplier * 5), a list of attacks, events related to the team, and a list of hit targets.

**Comment by bbriggs** [comment]
The score should be calculated at query time for the route. Use the category ID as a pivot/lookup to find the multiplier for each attack.

pesudocode:

```
total = 0
for _, attack := range attacks {
   total += attack.Category.Coefficient
}
```

Or we can add a method to the `Attack` struct that calculates the attack's value, then sum those
